// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzGIwjNMDUGrxJPFo7wX4heAtpCk3_N8',
    appId: '1:589594654448:web:2d3c1b76bbb70a6fa27435',
    messagingSenderId: '589594654448',
    projectId: 'appfit-43178',
    authDomain: 'appfit-43178.firebaseapp.com',
    storageBucket: 'appfit-43178.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWK6XJ9d4sRjUDlv6Qs3nctfXhmK_yPs',
    appId: '1:589594654448:android:9e9546bd28a6c279a27435',
    messagingSenderId: '589594654448',
    projectId: 'appfit-43178',
    storageBucket: 'appfit-43178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCIztlkWI_I4u8WN03Fs8MTDC8oXQ8sE',
    appId: '1:589594654448:ios:72383e898ef11ff1a27435',
    messagingSenderId: '589594654448',
    projectId: 'appfit-43178',
    storageBucket: 'appfit-43178.firebasestorage.app',
    iosBundleId: 'com.example.appfit',
  );
}
